# Name of the k8s cluster where the operator is deployed. Used in the `ApplicationRegistration` naming convention.

image: {}
imagePullPolicy: Always
nodeSelector: {}
tolerations: []
replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 400Mi
  limits:
    cpu: 1000m
    memory: 1500Mi
