# Name of the k8s cluster where the operator is deployed. Used in the `ApplicationRegistration` naming convention.

image: {}
imagePullPolicy: Always
nodeSelector: {}
tolerations: []
replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 400Mi
  limits:
    cpu: 1000m
    memory: 1500Mi

# Operator-specific configuration
drupalsiteOperator:
  # Default domain to expose DrupalSites that don't specify a `siteUrl`
  defaultDomain: "webtest.cern.ch"
  sitebuilderImage: "gitlab-registry.cern.ch/drupal/paas/cern-drupal-distribution/site-builder"
  nginxImage:  "gitlab-registry.cern.ch/drupal/paas/cern-drupal-distribution/nginx"
