# Name of the k8s cluster where the operator is deployed. Used in the `ApplicationRegistration` naming convention.

image: {}
imagePullPolicy: Always
nodeSelector: {}
tolerations: []
replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 400Mi
  limits:
    cpu: 1000m
    memory: 1500Mi

# Operator-specific configuration
drupalsiteOperator:
  sitebuilderImage: "gitlab-registry.cern.ch/drupal/paas/cern-drupal-distribution/site-builder"
  nginxImage:  "gitlab-registry.cern.ch/drupal/paas/cern-drupal-distribution/nginx"
  # Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
  logLevel: "3"
  # Zap Level at and above which stacktraces are captured (one of 'info', 'error')
  logStacktraceLevel: "error"
  defaultReleaseSpec: "RELEASE-2021.09.13T09-24-02Z"
