include:
  - project: 'paas-tools/infrastructure-ci'
    file: 'docker-images-ci-templates/DockerImages.gitlab-ci.yml'

stages:
  - build
  - go_test

variables:
  DEFAULT_DOMAIN: "webtest.cern.ch"
  RUNTIME_REPO: "https://gitlab.cern.ch/drupal/paas/drupal-runtime.git"

GoTest:
  stage: go_test
  image: golang:1.15
  script:
    - make test