workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

include:
  - project: 'paas-tools/infrastructure-ci'
    file: 'docker-images-ci-templates/DockerImages.gitlab-ci.yml'

stages:
  - test
  - build

variables:
  DEFAULT_DOMAIN: "webtest.cern.ch"

GoTest:
  stage: test
  image: golang:1.16
  script:
    - cp -r chart/drupalsite-operator/runtime-config/ /tmp/
    - make test
