# permissions for end users to view drupalprojectconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drupalprojectconfig-viewer-role
rules:
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalprojectconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalprojectconfigs/status
  verbs:
  - get
