
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webservices.cern.ch.webservices.cern.ch
  resources:
  - drupalsiterequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webservices.cern.ch.webservices.cern.ch
  resources:
  - drupalsiterequests/status
  verbs:
  - get
  - patch
  - update
