
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - dbod.cern.ch
  resources:
  - databaseclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbod.cern.ch
  resources:
  - databases
  verbs:
  - '*'
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/finalizers
  verbs:
  - update
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - schedules
  verbs:
  - '*'
- apiGroups:
  - webservices.cern.ch
  resources:
  - oidcreturnuris
  verbs:
  - '*'
