# permissions for end users to view supporteddrupalversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supporteddrupalversions-viewer-role
rules:
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - supporteddrupalversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - supporteddrupalversions/status
  verbs:
  - get
