apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSiteConfigOverride
metadata:
  name: drupalsiteconfigoverride-sample
spec:
  # Increase the replicas
  replicas: 4
  php:
    resources:
      requests:
        cpu: 1000m
        memory: 1G
      limits:
        cpu: 1000m
        memory: 1G
  # nginx:
  #   resources:
  #     requests:
  #       cpu: 40m
  #       memory: 10Mi
  #     limits:
  #       cpu: 2000m
  #       memory: 1.5Gi
  # webdav:
  #   resources:
  #     requests:
  #       cpu: 20m
  #       memory: 10Mi
  #     limits:
  #       cpu: 500m
  #       memory: 100Mi
  # phpexporter:
  #   resources:
  #     requests:
  #       cpu: 3m
  #       memory: 24Mi
  #     limits:
  #       cpu: 30m
  #       memory: 35Mi
  # cron:
  #   resources:
  #     requests:
  #       cpu: 10m
  #       memory: 10Mi
  #     limits:
  #       cpu: 80m
  #       memory: 20Mi
  # drupallogs:
  #   resources:
  #     requests:
  #       cpu: 4m
  #       memory: 10Mi
  #     limits:
  #       cpu: 15m
  #       memory: 15Mi
