apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  siteUrl: 
  - "drupalsite-ravineet.webtest.cern.ch"
  version:
    name: "v8.9-2"
    releaseSpec: "RELEASE-2021.10.26T15-33-59Z"
  configuration:
    qosClass: "critical"
    databaseClass: "standard"
    diskSize: "1Gi"
