apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: true
  version:
    name: "v8.9-1"
    releaseSpec: "RELEASE-2021.06.24T14-24-58Z"
  qosClass: "standard"
  databaseClass: "test"
  diskSize: "1Gi"
  mainSite: true
