apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: true
  version:
    name: "v8.9-1"
    releaseSpec: "RELEASE-2021.07.08T08-16-45Z"
  configuration:
    qosClass: "standard"
    databaseClass: "test"
    diskSize: "1Gi"
  mainSite: true
