apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSiteConfigOverride
metadata:
  name: drupalsiteconfigoverride-sample
spec:
  php:
    resources:
      requests:
        cpu: 1000m
        memory: 1G
      limits:
        cpu: 1000m
        memory: 1G
