apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  siteUrl:
  - "drupalsite-sample.webtest.cern.ch"
  version:
    name: "v9.2-1"
    releaseSpec: "RELEASE-2021.11.19T01-52-19Z"
  configuration:
    qosClass: "standard"
    databaseClass: "standard"
    diskSize: "1Gi"
    # Use the cloneFrom field to clone from an existing drupalsite
    # cloneFrom: "drupalsite-sample"
