apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: true
  drupalVersion: "8.9.14"
  environment:
    name: "production"
    qosClass: "standard"
    dbodClass: "test" 
  diskSize: "1Gi"
