apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: true
  version:
    name: "v8.9-1"
    releaseSpec: "RELEASE-2021.05.31T09-39-10Z"
  environment:
    name: "production"
    qosClass: "standard"
    databaseClass: "test"
  diskSize: "1Gi"
