apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: false
  drupalVersion: "8.9.13"
  diskSize: "5Gi"
  environment:
    name: "dev"
    qosClass: "standard"
    dbodClass: "test" 
  diskSize: "1Gi"
