apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  publish: true
  version:
    name: "8.9.14"
    releaseSpec: "stable"
  environment:
    name: "production"
    qosClass: "standard"
    databaseClass: "test" 
  diskSize: "1Gi"
