apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: drupalsite-sample
spec:
  siteUrl:
  - "drupalsite-sample.webtest.cern.ch"
  version:
    name: "v8.9-1"
    releaseSpec: "RELEASE-2021.10.06T01-14-07Z"
  configuration:
    qosClass: "standard"
    databaseClass: "standard"
    diskSize: "1Gi"
