apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: drush
spec:
  replicas: 1
  selector:
    deployment-config.name: drush
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: drush
    spec:
      initContainers:
      - name: siteBuilder-init
        image: gitlab-registry.cern.ch/drupal/paas/drupalsite-operator/site-builder
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /drupal-code
          name: drupal-directory
      containers:
      - name: sshd
        image: panubo/sshd
        imagePullPolicy: Always
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: /drupal-code
          name: drupal-directory
        - mountPath: /drupal-site-content
          name: drupal-pv
        resources: {}
      volumes:
      - name: drupal-directory
        emptyDir: {}
      - name: drupal-pv
        persistentVolumeClaim:
          claimName: drupal-pv