apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: buildconfigs.build.openshift.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: build.openshift.io
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: buildconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: buildconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: BuildConfig
  # either Namespaced or Cluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
