---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drupalsite-operator-leader-election-role
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drupalsite-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drupalsite-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: drupalsite-operator
