---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drupalsite-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites
  verbs:
  - "*"
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/finalizers
  verbs:
  - update
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/finalizers
  verbs:
  - '*'
- apiGroups:
  - dbod.cern
  resources:
  - dbodregistrations
  verbs:
  - '*'
- apiGroups:
  - dbod.cern
  resources:
  - databaseclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webservices.cern.ch
  resources:
  - oidcreturnuris
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drupalsite-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drupalsite-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drupalsite-operator-manager-role
subjects:
- kind: ServiceAccount
  name: drupalsite-operator
  namespace: {{ .Release.Namespace }}
