---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drupalsite-operator-manager-role
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites
  verbs:
  - "*"
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/finalizers
  verbs:
  - update
- apiGroups:
  - drupal.webservices.cern.ch
  resources:
  - drupalsites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drupalsite-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drupalsite-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drupalsite-operator-manager-role
subjects:
- kind: ServiceAccount
  name: drupalsite-operator
