# configures the namespaces where our operator is made available.
# The OperatorGroup applies to all operators (CSVs) in its parent namespace.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    # this annotation will be managed by the OLM. If we set it, ArgoCD will be continuously out of sync.
    # olm.providedAPIs: DrupalSite.v1alpha1.drupal.webservices.cern.ch
  name: drupalsite-operator
spec: {}
# spec.targetNamespaces is not set, this means deploy to all namespaces
# (OLM will copy the operator CSV to each namespace in the cluster!)
